---
title: "数据驱动的生态学研究方法-作业1"
author: "余春兰"
date: '2022-03-13'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mydata<-iris[,1:4]#读取数据的1-4列
x<-mydata$Sepal.Length
y<-mydata$Sepal.Width
cor(x,y,use="everything",method="pearson")#计算花萼长、花萼宽相关系数
cor.test(x,y)#相关的显著性检验
res<-cor.test(x,y)
res$p.value#提取P值
res$conf.int#置信区间
library("corrplot")
res_cor<-cor(mydata)#定义绘图变量
corrplot(res_cor)#输出关系图
cor(mydata)#对矩阵变量进行相关分析
library("psych")
corr.test(mydata,use="complete",method = "pearson",adjust = "none")
res$conf.int#输出相关性
res$p.value#输出P值
#########################################################
setwd("G:/数据")
mydata<-read.csv("xy.csv",header = T)
x1<-mydata$food
x2<-mydata$seggs
x3<-mydata$workers
y1<-mydata$foragers
y2<-mydata$distance
test<-data.frame(x1,x2,x3,y1,y2)#用数据框形式表达
test<-scale(test)#将数据标准化，消除里纲影响
pairs(test)#绘制散点图
cor.test(x1,y1)
cor.test(x1,y2)
cor.test(x2,y1)
cor.test(x2,y2)
cor.test(x3,y1)
cor.test(x3,y2)
cor.test(x1,x2)
cor.test(x2,x3)
ca<-cancor(test[,1:3],test[,4:5])#做典型相关分析
ca
ca<-cancor(test[,1:3],test[,4:5],xcenter=T,ycenter=T)#相关分析并对数据进行中心化处理
ca
U<-as.matrix(test[,1:3]%*% ca$xcoef)#计算数据在典型变量下的得分
V<-as.matrix(test[,4:5]%*% ca$ycoef)#计算数据在典型变量下的得分
par(mfrow=c(1,2))
plot(U[,1],V[,1],xlab = "U1",ylab = "V1")#画出数据散点图
plot(U[,2],V[,2],xlab = "U2",ylab = "V2")
```


```{r}
age<-c(20,22,24,26,28,30,32,34,36,38,40,42)
collection<-c(8.4,9.5,11.8,10.4,13.3,14.8,
              13.2,14.7,16.4,16.5,18.9,18.5)
plot(age~collection)
reg<-lm(age~collection)
abline(reg,col="red")
summary(reg)
#########################################################
boxplot(count~spray,data=InsectSprays)
boxplot(count~spray,data=InsectSprays,col="red")
#########################################################
x<-runif(50,0,2)
y<-runif(50,0,2)
plot(x,y,main = "散点图",xlab="横坐标",ylab="纵坐标")
text(0.6,0.6,"text at (0.6,0.6)")
abline(h=0.6,v=0.6)
plot(x,y,type = "n",xlab = "",ylab = "",axes=F)
points(x,y)
axis(1)
box()
title(main = "Main title",sub = "subtitle",
      xlab = "x-label",ylab ="y-label" )
#########################################################
par(mfrow=c(2,2))
x<-rnorm(100)#生成随机数
hist(x,freq = F)#绘制直方图
curve(dnorm(x),add=T)#添加曲线
h<-hist(x,plot = F)#绘制直方图
ylim<-range(0,h$density,dnorm(0))#设定纵轴的取值范围
hist(x,freq=F,ylim = ylim)#绘制直方图
curve(dnorm(x),add=T,col="red")#添加红色曲线

```

